### ISSUE TITLE
KlipperLCD requires max_accel_to_decel to be defined

### ISSUE THREAD

**Issue by Joldiges** [joakimtoe/KlipperLCD#11]
AFAIK, max_accel_to_decel isn't enabled in configurations that don't have input-shaper (yet) enabled.
KlipperLCD is requiring it to be defined.  Perhaps have this script include use the dictionary `default` param to return `-1` or `N/A`.  (this is what I did for my own instance)

**Comment by jofland** [comment]
> AFAIK, max_accel_to_decel isn't enabled in configurations that don't have input-shaper (yet) enabled. KlipperLCD is requiring it to be defined. Perhaps have this script include use the dictionary `default` param to return `-1` or `N/A`. (this is what I did for my own instance)

Could you please post the code snippets of your workaround?

**Comment by Joldiges** [comment]
I'll raise a PR #12 is rasied

[max_accel_to_decel has officially been deprecated ](https://www.klipper3d.org/Config_Changes.html)

> 20240313: The max_accel_to_decel parameter in the [printer] config section has been deprecated. The ACCEL_TO_DECEL parameter of the SET_VELOCITY_LIMIT command has been deprecated. The printer.toolhead.max_accel_to_decel status has been removed. Use the [minimum_cruise_ratio parameter](https://www.klipper3d.org/Config_Reference.html#printer) instead. The deprecated features will be removed in the near future, and using them in the interim may result in subtly different behavior.

**Comment by Gpy13** [comment]
> AFAIK, max_accel_to_decel isn't enabled in configurations that don't have input-shaper (yet) enabled. KlipperLCD is requiring it to be defined. Perhaps have this script include use the dictionary `default` param to return `-1` or `N/A`. (this is what I did for my own instance)

I'm sorry for excuse 
Could you please provide the solution of your own with this 'default -1'.
Where should I write it?

please, give line by line instruction, thanx
